<?php
    
    header("refresh: 60");
    
    $data2 = file_get_contents('https://pms.healtopedia.com/productjson.php');
    $data2 = json_decode($data2, true);

    $conn = mysqli_connect("localhost","myhealtopedia","Healit20.","db_pms");
        
    foreach ($data2 as $row2){
        $packageid = $row2['id'];
        $packagename = $row2['name'];
        $packageprice = $row2['price'];
        if (strpos("'".$row2['categories'][5]['name']."'",'KPJ') != false || strpos("'".$row2['categories'][5]['name']."'",'Sunway') != false || strpos("'".$row2['categories'][5]['name']."'",'Healtopedia') != false || strpos("'".$row2['categories'][5]['name']."'",'Disinfection') != false || strpos("'".$row2['categories'][5]['name']."'",'Klinik') != false || strpos("'".$row2['categories'][5]['name']."'",'Wellness') != false || strpos("'".$row2['categories'][5]['name']."'",'Medicare') != false || strpos("'".$row2['categories'][5]['name']."'",'Clinic') != false || strpos("'".$row2['categories'][5]['name']."'",'BeLive') != false || strpos("'".$row2['categories'][5]['name']."'",'BENPHYSIO') != false || strpos("'".$row2['categories'][5]['name']."'",'CryoFit') != false || strpos("'".$row2['categories'][5]['name']."'",'International') != false || strpos("'".$row2['categories'][5]['name']."'",'Regen') != false || strpos("'".$row2['categories'][5]['name']."'",'Soul') != false || strpos("'".$row2['categories'][5]['name']."'",'ALPS') != false || strpos("'".$row2['categories'][5]['name']."'",'Home') != false || strpos("'".$row2['categories'][5]['name']."'",'Dokter4U') != false || strpos("'".$row2['categories'][5]['name']."'",'Thomson') != false || strpos("'".$row2['categories'][5]['name']."'",'Prince') != false || strpos("'".$row2['categories'][5]['name']."'",'Timberland') != false || strpos("'".$row2['categories'][5]['name']."'",'Imperial') != false) {
                $hospname = $row2['categories'][5]['name'];

        }elseif (strpos("'".$row2['categories'][4]['name']."'",'KPJ') != false || strpos("'".$row2['categories'][4]['name']."'",'Sunway') != false || strpos("'".$row2['categories'][4]['name']."'",'Healtopedia') != false || strpos("'".$row2['categories'][4]['name']."'",'Disinfection') != false || strpos("'".$row2['categories'][4]['name']."'",'Klinik') != false || strpos("'".$row2['categories'][4]['name']."'",'Wellness') != false || strpos("'".$row2['categories'][4]['name']."'",'Medicare') != false || strpos("'".$row2['categories'][4]['name']."'",'Clinic') != false || strpos("'".$row2['categories'][4]['name']."'",'BeLive') != false || strpos("'".$row2['categories'][4]['name']."'",'BENPHYSIO') != false || strpos("'".$row2['categories'][4]['name']."'",'CryoFit') != false || strpos("'".$row2['categories'][4]['name']."'",'International') != false || strpos("'".$row2['categories'][4]['name']."'",'Regen') != false || strpos("'".$row2['categories'][4]['name']."'",'Soul') != false || strpos("'".$row2['categories'][4]['name']."'",'ALPS') != false || strpos("'".$row2['categories'][4]['name']."'",'Home') != false || strpos("'".$row2['categories'][4]['name']."'",'Dokter4U') != false || strpos("'".$row2['categories'][4]['name']."'",'Thomson') != false || strpos("'".$row2['categories'][4]['name']."'",'Prince') != false || strpos("'".$row2['categories'][4]['name']."'",'Timberland') != false || strpos("'".$row2['categories'][4]['name']."'",'Imperial') != false) {
               $hospname = $row2['categories'][4]['name'];

        }elseif (strpos("'".$row2['categories'][3]['name']."'",'KPJ') != false || strpos("'".$row2['categories'][3]['name']."'",'Sunway') != false || strpos("'".$row2['categories'][3]['name']."'",'Healtopedia') != false || strpos("'".$row2['categories'][3]['name']."'",'Disinfection') != false || strpos("'".$row2['categories'][3]['name']."'",'Klinik') != false || strpos("'".$row2['categories'][3]['name']."'",'Wellness') != false || strpos("'".$row2['categories'][3]['name']."'",'Medicare') != false || strpos("'".$row2['categories'][3]['name']."'",'Clinic') != false || strpos("'".$row2['categories'][3]['name']."'",'BeLive') != false || strpos("'".$row2['categories'][3]['name']."'",'BENPHYSIO') != false || strpos("'".$row2['categories'][3]['name']."'",'CryoFit') != false || strpos("'".$row2['categories'][3]['name']."'",'International') != false || strpos("'".$row2['categories'][3]['name']."'",'Regen') != false || strpos("'".$row2['categories'][3]['name']."'",'Soul') != false || strpos("'".$row2['categories'][3]['name']."'",'ALPS') != false || strpos("'".$row2['categories'][3]['name']."'",'Home') != false || strpos("'".$row2['categories'][3]['name']."'",'Dokter4U') != false || strpos("'".$row2['categories'][3]['name']."'",'Thomson') != false || strpos("'".$row2['categories'][3]['name']."'",'Prince') != false || strpos("'".$row2['categories'][4]['name']."'",'Timberland') != false || strpos("'".$row2['categories'][3]['name']."'",'Imperial') != false) {
                $hospname = $row2['categories'][3]['name'];

        }elseif (strpos("'".$row2['categories'][2]['name']."'",'KPJ') != false || strpos("'".$row2['categories'][2]['name']."'",'Sunway') != false || strpos("'".$row2['categories'][2]['name']."'",'Healtopedia') != false || strpos("'".$row2['categories'][2]['name']."'",'Disinfection') != false || strpos("'".$row2['categories'][2]['name']."'",'Klinik') != false || strpos("'".$row2['categories'][2]['name']."'",'Wellness') != false || strpos("'".$row2['categories'][2]['name']."'",'Medicare') != false || strpos("'".$row2['categories'][2]['name']."'",'Clinic') != false || strpos("'".$row2['categories'][2]['name']."'",'BeLive') != false || strpos("'".$row2['categories'][2]['name']."'",'BENPHYSIO') != false || strpos("'".$row2['categories'][2]['name']."'",'CryoFit') != false || strpos("'".$row2['categories'][2]['name']."'",'International') != false || strpos("'".$row2['categories'][2]['name']."'",'Regen') != false || strpos("'".$row2['categories'][2]['name']."'",'Soul') != false || strpos("'".$row2['categories'][2]['name']."'",'ALPS') != false || strpos("'".$row2['categories'][2]['name']."'",'Home') != false || strpos("'".$row2['categories'][2]['name']."'",'Dokter4U') != false || strpos("'".$row2['categories'][2]['name']."'",'Thomson') != false || strpos("'".$row2['categories'][2]['name']."'",'Prince') != false || strpos("'".$row2['categories'][2]['name']."'",'Timberland') != false || strpos("'".$row2['categories'][2]['name']."'",'Imperial') != false) {
                $hospname = $row2['categories'][2]['name'];

        }elseif (strpos("'".$row2['categories'][1]['name']."'",'KPJ') != false || strpos("'".$row2['categories'][1]['name']."'",'Sunway') != false || strpos("'".$row2['categories'][1]['name']."'",'Healtopedia') != false || strpos("'".$row2['categories'][1]['name']."'",'Disinfection') != false || strpos("'".$row2['categories'][1]['name']."'",'Klinik') != false || strpos("'".$row2['categories'][1]['name']."'",'Wellness') != false || strpos("'".$row2['categories'][1]['name']."'",'Medicare') != false || strpos("'".$row2['categories'][1]['name']."'",'Clinic') != false || strpos("'".$row2['categories'][1]['name']."'",'BeLive') != false || strpos("'".$row2['categories'][1]['name']."'",'BENPHYSIO') != false || strpos("'".$row2['categories'][1]['name']."'",'CryoFit') != false || strpos("'".$row2['categories'][1]['name']."'",'International') != false || strpos("'".$row2['categories'][1]['name']."'",'Regen') != false || strpos("'".$row2['categories'][1]['name']."'",'Soul') != false || strpos("'".$row2['categories'][1]['name']."'",'ALPS') != false || strpos("'".$row2['categories'][1]['name']."'",'Home') != false || strpos("'".$row2['categories'][1]['name']."'",'Dokter4U') != false || strpos("'".$row2['categories'][1]['name']."'",'Thomson') != false || strpos("'".$row2['categories'][1]['name']."'",'Prince') != false || strpos("'".$row2['categories'][1]['name']."'",'Timberland') != false || strpos("'".$row2['categories'][1]['name']."'",'Imperial') != false) {
                $hospname = $row2['categories'][1]['name'];

        }elseif (strpos("'".$row2['categories'][0]['name']."'",'KPJ') != false || strpos("'".$row2['categories'][0]['name']."'",'Sunway') != false || strpos("'".$row2['categories'][0]['name']."'",'Healtopedia') != false || strpos("'".$row2['categories'][0]['name']."'",'Disinfection') != false || strpos("'".$row2['categories'][0]['name']."'",'Klinik') != false || strpos("'".$row2['categories'][0]['name']."'",'Wellness') != false || strpos("'".$row2['categories'][0]['name']."'",'Medicare') != false || strpos("'".$row2['categories'][0]['name']."'",'Clinic') != false || strpos("'".$row2['categories'][0]['name']."'",'BeLive') != false || strpos("'".$row2['categories'][0]['name']."'",'BENPHYSIO') != false || strpos("'".$row2['categories'][0]['name']."'",'CryoFit') != false || strpos("'".$row2['categories'][0]['name']."'",'International') != false || strpos("'".$row2['categories'][0]['name']."'",'Regen') != false || strpos("'".$row2['categories'][0]['name']."'",'Soul') != false || strpos("'".$row2['categories'][0]['name']."'",'ALPS') != false || strpos("'".$row2['categories'][0]['name']."'",'Home') != false || strpos("'".$row2['categories'][0]['name']."'",'Dokter4U') != false || strpos("'".$row2['categories'][0]['name']."'",'Thomson') != false || strpos("'".$row2['categories'][0]['name']."'",'Prince') != false || strpos("'".$row2['categories'][0]['name']."'",'Timberland') != false || strpos("'".$row2['categories'][0]['name']."'",'Imperial') != false) {
                $hospname = $row2['categories'][0]['name'];
        }
        
        $sql = "INSERT INTO packagewoo SET package_id = '$packageid', package_name = '$packagename', package_hosp = '$hospname', package_price = '$packageprice'";
        mysqli_query($conn, $sql);
    }
?>
